version: '3.7'

services:

  configserver:
    image: confsvr
    ports:
      - "8888:8888"
    networks:
      - jazzified

  eurekaserver:
    image: eureka
    ports:
      - "8761:8761"
    depends_on:
      - configserver
    networks:
      - jazzified

  spotifyservice:
    image: spotify
    ports:
      - "8091:8091"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      - jazzified

  artistservice:
    image: artist-persistence
    ports:
      - "8092:8092"
    depends_on:
      - configserver
      - eurekaserver
      - spotifyservice
    networks:
      - jazzified

networks:
  jazzified:
