version: '3.7'

services:

  artistdatabase:
    image: mysql:8
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jazzified
    networks:
      - jazzified

  configserver:
    image: confsvr
    ports:
      - "8888:8888"
    restart: on-failure
    networks:
      - jazzified

  eurekaserver:
    image: eureka
    ports:
      - "8761:8761"
    restart: on-failure
    depends_on:
      configserver:
        condition: service_started
    networks:
      - jazzified

  spotifyservice:
    image: spotify
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      - jazzified

  artistservice:
    image: artist
    ports:
      - "8092:8092"
    restart: always
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
      spotifyservice:
        condition: service_started
      artistdatabase:
        condition: service_started
    networks:
      - jazzified

networks:
  jazzified:
