eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/ '
  instance:
    prefer-ip-address: true
server:
  port: 8093
spring:
  cloud:
    gateway:
      routes:
        - id: spotifySearchModule
          uri: lb://spotify-service
          predicates:
            - Path=/api/v1/jazzified/spotify/**
        - id: artistCreateModule
          uri: lb://artist-persistence-service
          predicates:
            - Path=/api/v1/jazzified/artist/**
      eureka:
        client:
          fetch-registry: true
          register-with-eureka: true
          service-url:
            defaultZone: 'http://localhost:8761/eureka/ '
        instance:
          prefer-ip-address: true